<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__attachment-woocommerce_thumbnail size-_5f269b</name>
   <tag></tag>
   <elementGuidId>bfa2c81c-d9e2-4047-ba21-2122e009e0a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/ul/li/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.attachment-woocommerce_thumbnail.size-woocommerce_thumbnail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>626094e7-1119-4a2b-a0dc-74dc883166e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>324</value>
      <webElementGuid>0f1087aa-ab67-4d4b-98e2-902c5dfda6dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>324</value>
      <webElementGuid>3b77ab80-7905-46b7-a1fc-f8f5e1352d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://craferia.com/wp-content/uploads/2023/08/MUDHA-156B-324x324.jpeg?v=1701777669</value>
      <webElementGuid>17a8a2fc-ffe7-4fc3-99c2-e032bb1cef4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-woocommerce_thumbnail size-woocommerce_thumbnail</value>
      <webElementGuid>ff2c0fe6-0454-4a5d-bfc3-6df2ddbbc9eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>a61fc6fc-b927-44df-9356-f50c988681b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fetchpriority</name>
      <type>Main</type>
      <value>high</value>
      <webElementGuid>eec57c86-2a79-437c-a5cb-152ac9782d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://craferia.com/wp-content/uploads/2023/08/MUDHA-156B-324x324.jpeg?v=1701777669 324w, https://craferia.com/wp-content/uploads/2023/08/MUDHA-156B-300x300.jpeg?v=1701777669 300w, https://craferia.com/wp-content/uploads/2023/08/MUDHA-156B-150x150.jpeg?v=1701777669 150w, https://craferia.com/wp-content/uploads/2023/08/MUDHA-156B-768x768.jpeg?v=1701777669 768w, https://craferia.com/wp-content/uploads/2023/08/MUDHA-156B-416x416.jpeg?v=1701777669 416w, https://craferia.com/wp-content/uploads/2023/08/MUDHA-156B-100x100.jpeg?v=1701777669 100w, https://craferia.com/wp-content/uploads/2023/08/MUDHA-156B.jpeg?v=1701777669 960w</value>
      <webElementGuid>86fe4209-0c80-4bb7-9898-b563b1417b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 324px) 100vw, 324px</value>
      <webElementGuid>b6517857-0271-4134-8a82-60d10e57a3b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/ul[@class=&quot;products columns-4&quot;]/li[@class=&quot;product type-product post-6447 status-publish first instock product_cat-bamboo-furniture product_cat-hotel-restaurant-furniture has-post-thumbnail taxable shipping-taxable purchasable product-type-simple&quot;]/a[@class=&quot;woocommerce-LoopProduct-link woocommerce-loop-product__link&quot;]/img[@class=&quot;attachment-woocommerce_thumbnail size-woocommerce_thumbnail&quot;]</value>
      <webElementGuid>49a8e359-4d01-4c62-84f0-893070524692</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/ul/li/a/img</value>
      <webElementGuid>ab0a9d9d-2ce2-40de-a578-805cac96a110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://craferia.com/wp-content/uploads/2023/08/MUDHA-156B-324x324.jpeg?v=1701777669')]</value>
      <webElementGuid>81a83bf1-33b0-4c45-b1c0-f24fba85af11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/img</value>
      <webElementGuid>45c8b54b-019a-45f9-834e-1a3bead23a29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://craferia.com/wp-content/uploads/2023/08/MUDHA-156B-324x324.jpeg?v=1701777669']</value>
      <webElementGuid>11b9fa16-76a4-49db-8220-ee953da14011</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
