<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Furnishings</name>
   <tag></tag>
   <elementGuidId>0176bae5-5212-432b-bfd3-92c8b6e532e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26709']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26709 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ecbdf220-d5e5-4f2b-8371-dab7abf05b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/furnishings/</value>
      <webElementGuid>9b78a15e-2b99-4d68-acf1-74ac29ed1bcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>e0e802f1-c9ac-4112-9b60-0c58b5ecafb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Furnishings</value>
      <webElementGuid>a43ed434-3084-47fa-bf00-eb49fbecc709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26709&quot;)/a[1]</value>
      <webElementGuid>7af719c6-31dc-4654-8715-fc3d0b1def93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26709']/a</value>
      <webElementGuid>4a944162-a41f-4602-9eb3-d8c8e3044f2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Furnishings')]</value>
      <webElementGuid>2b8477cb-d198-4e85-9482-61a9f2811cbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mudha Table'])[1]/following::a[1]</value>
      <webElementGuid>54b34b15-a418-41db-92d1-33a47da5c2d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mudha chairs'])[1]/following::a[2]</value>
      <webElementGuid>d4db0491-bda3-4200-ac40-320761352722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cushions'])[1]/preceding::a[1]</value>
      <webElementGuid>b14155b1-c10a-4f3d-805d-cdb379c7f6fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Placemats &amp; Runners'])[1]/preceding::a[2]</value>
      <webElementGuid>98006afc-da88-4544-9208-b7471d877196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Furnishings']/parent::*</value>
      <webElementGuid>0ab36bbf-93eb-41e1-b6bf-3d3e4d827e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/furnishings/')]</value>
      <webElementGuid>0d0b37ea-d9a6-4955-b8f7-67cf1a86eb54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a</value>
      <webElementGuid>f8614e3b-c858-4017-9080-0624bff8fc41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/furnishings/' and (text() = 'Furnishings' or . = 'Furnishings')]</value>
      <webElementGuid>d69c7a57-a639-4448-b632-3eec64b0a390</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
