<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tapestry</name>
   <tag></tag>
   <elementGuidId>5c5c6a98-486b-47fb-8fd6-e3e86d2c06be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26725']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26725 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>166839d0-1a4d-47f2-ac30-7a1423ef7ef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/tapestry/</value>
      <webElementGuid>e10123ba-d3b4-47f0-ab7f-c1085ea5c490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tapestry</value>
      <webElementGuid>37d40d48-6e36-41a5-a3d3-44a80aadfe04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26725&quot;)/a[1]</value>
      <webElementGuid>bd3cbce3-fd1d-489f-9c3a-cfce35f12afc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26725']/a</value>
      <webElementGuid>07a877c5-60b2-45a4-957b-19555a9d7120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tapestry')]</value>
      <webElementGuid>870b9c39-df0e-4fe7-81ad-b03a14141683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blankets &amp; Quilts'])[1]/following::a[1]</value>
      <webElementGuid>5e8e839a-fbf6-4064-851f-c2514376dd16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Double Bedsheet'])[1]/following::a[2]</value>
      <webElementGuid>6aef18d0-77dd-4eaf-9c89-4bc9484864d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Single Tapestry'])[1]/preceding::a[1]</value>
      <webElementGuid>1c37968c-4a2e-455a-a327-b3f7e1656318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Round Tapestry'])[1]/preceding::a[2]</value>
      <webElementGuid>ef62b518-b431-44d7-806b-bcfa5cae79b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tapestry']/parent::*</value>
      <webElementGuid>71248cbd-40cc-4333-874f-dec92329be29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/tapestry/')]</value>
      <webElementGuid>e1ca5193-33c4-48be-8c9e-260368806619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/ul/li[5]/a</value>
      <webElementGuid>7cbc4931-352f-4749-a096-8707de776842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/tapestry/' and (text() = 'Tapestry' or . = 'Tapestry')]</value>
      <webElementGuid>ee6ca1ae-3404-456c-a246-22cee9f65fad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
