<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Add to cart_attachment-woocommerce_thum_569712</name>
   <tag></tag>
   <elementGuidId>3432e931-a47f-4b9d-b264-92909a546cdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/ul/li[2]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.product.type-product.post-6436.status-publish.instock.product_cat-bamboo-chair.has-post-thumbnail.taxable.shipping-taxable.purchasable.product-type-simple > a.woocommerce-LoopProduct-link.woocommerce-loop-product__link > img.attachment-woocommerce_thumbnail.size-woocommerce_thumbnail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>32dc7cff-9b3e-46de-a3f9-db84a53dcda3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>324</value>
      <webElementGuid>25ef71de-edbb-4185-9611-e46f7b05ba31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>324</value>
      <webElementGuid>40ae2c6f-e83d-4900-8f40-1f107d661691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://craferia.com/wp-content/uploads/2023/08/MUDHA-150A-324x324.jpeg?v=1701777678</value>
      <webElementGuid>f40f374e-4355-4ac6-bbcb-f1c9f325f409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-woocommerce_thumbnail size-woocommerce_thumbnail</value>
      <webElementGuid>04a95244-352e-4333-aef7-f188cbe6c3a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>70b344e2-b60e-4116-8f50-d1f67f433438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://craferia.com/wp-content/uploads/2023/08/MUDHA-150A-324x324.jpeg?v=1701777678 324w, https://craferia.com/wp-content/uploads/2023/08/MUDHA-150A-300x300.jpeg?v=1701777678 300w, https://craferia.com/wp-content/uploads/2023/08/MUDHA-150A-150x150.jpeg?v=1701777678 150w, https://craferia.com/wp-content/uploads/2023/08/MUDHA-150A-768x768.jpeg?v=1701777678 768w, https://craferia.com/wp-content/uploads/2023/08/MUDHA-150A-416x416.jpeg?v=1701777678 416w, https://craferia.com/wp-content/uploads/2023/08/MUDHA-150A-100x100.jpeg?v=1701777678 100w, https://craferia.com/wp-content/uploads/2023/08/MUDHA-150A.jpeg?v=1701777678 960w</value>
      <webElementGuid>de6ce9f4-9cbd-41c4-be75-22534af22931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 324px) 100vw, 324px</value>
      <webElementGuid>3dc0eacd-f2c4-45a3-8c31-4103d1a57acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/ul[@class=&quot;products columns-4&quot;]/li[@class=&quot;product type-product post-6436 status-publish instock product_cat-bamboo-chair has-post-thumbnail taxable shipping-taxable purchasable product-type-simple&quot;]/a[@class=&quot;woocommerce-LoopProduct-link woocommerce-loop-product__link&quot;]/img[@class=&quot;attachment-woocommerce_thumbnail size-woocommerce_thumbnail&quot;]</value>
      <webElementGuid>c91e877b-ca9c-4f5d-983b-7a6c2e789257</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/ul/li[2]/a/img</value>
      <webElementGuid>ab046810-1c22-4ce0-847f-69ec22cccc33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://craferia.com/wp-content/uploads/2023/08/MUDHA-150A-324x324.jpeg?v=1701777678')]</value>
      <webElementGuid>875f79c3-253a-42e1-b6f5-fe9315a41681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/img</value>
      <webElementGuid>bdbba5a8-bba7-464e-a646-80563a29a0e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://craferia.com/wp-content/uploads/2023/08/MUDHA-150A-324x324.jpeg?v=1701777678']</value>
      <webElementGuid>92b6ad17-3f06-4879-8dc7-c89b565144c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
