<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Furnishings</name>
   <tag></tag>
   <elementGuidId>d61df55a-1054-4dfc-81be-4119da4f8f6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26709']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26709 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a2346b61-eceb-48dc-9b17-b3a8ff48c2e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/furnishings/</value>
      <webElementGuid>5ca6699a-abd9-4457-bcce-e454f2fe44d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Furnishings</value>
      <webElementGuid>21f9a8c2-6978-4651-a17e-a72a59362df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26709&quot;)/a[1]</value>
      <webElementGuid>256b805b-c68c-4f12-8729-deb092d080e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26709']/a</value>
      <webElementGuid>557e5838-d6f8-4fb9-84cb-7831627cfdbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Furnishings')]</value>
      <webElementGuid>433736d0-6f4a-4e4c-984a-92753a4f602c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mudha Table'])[1]/following::a[1]</value>
      <webElementGuid>b3400a32-e31a-485b-9310-a57ad1f75aa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mudha chairs'])[1]/following::a[2]</value>
      <webElementGuid>d04002fc-714b-4d8c-bcc1-028a5336d62c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cushions'])[1]/preceding::a[1]</value>
      <webElementGuid>88b8aa67-ca27-4d1f-a975-7b9365db74c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Placemats &amp; Runners'])[1]/preceding::a[2]</value>
      <webElementGuid>b7010d91-22f0-45ca-904c-1930fa28316e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Furnishings']/parent::*</value>
      <webElementGuid>90179c07-c540-4443-84b8-bc542af9834e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/furnishings/')]</value>
      <webElementGuid>31df9eb9-1049-4741-a2df-6f54b07e35e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a</value>
      <webElementGuid>3812087f-0dec-45b4-a372-ba101e9936bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/furnishings/' and (text() = 'Furnishings' or . = 'Furnishings')]</value>
      <webElementGuid>06711b91-94f5-43d2-9203-7c9141637fb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
