<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Outdoor Furniture</name>
   <tag></tag>
   <elementGuidId>a426f26f-3d9d-49d2-a45b-b74b7429656e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26702']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26702 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f6136230-4e15-4f64-a8ea-bdd5e2f10665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/outdoor-furniture/</value>
      <webElementGuid>07ebefe5-214d-4528-b3c3-3a7503bd519c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Outdoor Furniture</value>
      <webElementGuid>316532d1-d551-4114-9f4a-0916d0ed4499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26702&quot;)/a[1]</value>
      <webElementGuid>0aae0f88-a818-4772-bf85-ae51e0d7f6fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26702']/a</value>
      <webElementGuid>5ba28741-0a6f-4824-9d7c-a575e11769b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Outdoor Furniture')]</value>
      <webElementGuid>47933e8a-6a1c-4d88-93b9-94716018e53e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cane Furniture'])[1]/following::a[1]</value>
      <webElementGuid>29159467-a637-4e52-9d72-11162ea860fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wooden Furnitures'])[1]/following::a[2]</value>
      <webElementGuid>6612b764-44f1-4a31-90d0-af3cf49859de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hotel &amp; Restaurant Furniture'])[1]/preceding::a[1]</value>
      <webElementGuid>7bb5d5d7-c73c-4a25-9400-f98fc3f961e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mudha'])[1]/preceding::a[2]</value>
      <webElementGuid>c94af57b-8c8f-43f4-9880-e2136d309518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Outdoor Furniture']/parent::*</value>
      <webElementGuid>408bfaef-4cfb-40f4-be74-3321483497cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/outdoor-furniture/')]</value>
      <webElementGuid>ac9c87ac-30e0-4441-8d91-7ec96fb18bfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>165331f6-f0fd-4ccf-bce6-f50ce3bb57be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/outdoor-furniture/' and (text() = 'Outdoor Furniture' or . = 'Outdoor Furniture')]</value>
      <webElementGuid>4850d2e5-2ada-4529-9a9b-af3b345bc093</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
