<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>c72e2f3e-6247-4f25-b6c5-7d6e68588df6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div/nav/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.next.page-numbers</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ac42bc76-70f6-4fb0-b978-22693aa178a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>next page-numbers</value>
      <webElementGuid>881c6167-2d2e-4508-bb8b-c3bca2550e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/cane-fruit-baskets/page/2/</value>
      <webElementGuid>cd3df94a-25a7-44b8-9517-10910c5fc911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>→</value>
      <webElementGuid>d93fda22-a364-4023-b856-99dae8386801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;storefront-sorting&quot;]/nav[@class=&quot;woocommerce-pagination&quot;]/ul[@class=&quot;page-numbers&quot;]/li[3]/a[@class=&quot;next page-numbers&quot;]</value>
      <webElementGuid>7f10241a-a0b4-44be-bc05-c7a85c6a7b4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/nav/ul/li[3]/a</value>
      <webElementGuid>0d38f001-9a59-440a-9bdb-a99b6ee296ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'→')]</value>
      <webElementGuid>0e451042-99aa-4590-9f92-52f86a26b47d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cane Baskets'])[3]/following::a[2]</value>
      <webElementGuid>23b57910-2e45-4a72-ba33-3b104972ce70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[2]/following::a[2]</value>
      <webElementGuid>29446d7f-2dc3-4470-b71a-aa3458567a61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹'])[2]/preceding::a[1]</value>
      <webElementGuid>3f399243-4222-453e-b4bd-6f0b59b8e513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='→']/parent::*</value>
      <webElementGuid>eac67f24-8aca-4419-ae72-5adbe2386e8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://craferia.com/cane-fruit-baskets/page/2/')])[2]</value>
      <webElementGuid>705ace67-4602-474c-b51e-c47c8fb3c761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[3]/a</value>
      <webElementGuid>af6e78ba-1471-4839-9b0d-5c1359816361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/cane-fruit-baskets/page/2/' and (text() = '→' or . = '→')]</value>
      <webElementGuid>33e3e588-4463-43ba-9c94-e6b916f798eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
